// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/results': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/admin/results.get').default>>>>
    }
    '/api/verify-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/verify-otp.post').default>>>>
    }
    '/api/vote': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/vote.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.6_db0@0.3.4_ioredis@5.10.1_magicast@0.5.3_nuxt@3.21.6_@parcel+w_81ded020cc27bc036872a53d7ba5d228/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}