// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/27/2026, 10:50:01 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/plugins/**/*.{js,ts,mjs}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/composables/**/*.{js,ts,mjs}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/utils/**/*.{js,ts,mjs}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marc_hbb/Documents/Checkit/dev/evad-ceremony-vote/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;